/* Core module of HTTP enabling Node.js networking */
const http = require('http');

/* List of possible fortune cookie sayings */
const fortuneSayingsList = [
    "Today it’s up to you to create the peacefulness you long for.",
    "A friend asks only for your time not your money.",
    "Today it’s up to you to create the peacefulness you long for.",
    "A friend asks only for your time not your money.",
    "If you refuse to accept anything but the best, you very often get it.",
    "A smile is your passport into the hearts of others.",
    "A good way to keep healthy is to eat more Chinese food.",
    "Your high-minded principles spell success.",
    "Hard work pays off in the future, laziness pays off now.",
    "Change can hurt, but it leads a path to something better.",
    "Enjoy the good luck a companion brings you.",
    "People are naturally attracted to you.",
    "A chance meeting opens new doors to success and friendship.",
    "You learn from your mistakes...  You will learn a lot today.",
    "If you have something good in your life, don’t let it go!",
    "What ever you’re goal is in life, embrace it visualize it, and for it will be yours.",
    "Your shoes will make you happy today.",
    "You cannot love life until you live the life you love.",
    "Be on the lookout for coming events; They cast their shadows beforehand.",
    "Land is always on the mind of a flying bird.",
    "The man or woman you desire feels the same about you.",
    "Meeting adversity well is the source of your strength.",
    "A dream you have will come true.",
    "Our deeds determine us, as much as we determine our deeds.",
    "Never give up.  You’re not a failure if you don’t give up.",
    "You will become great if you believe in yourself.",
    "There is no greater pleasure than seeing your loved ones prosper.",
    "You will marry your lover.",
    "A very attractive person has a message for you.",
    "You already know the answer to the questions lingering inside your head.",
    "It is now, and in this world, that we must live.",
    "You must try, or hate yourself for not trying.",
    "You can make your own happiness.",
    "being week is nothing to be ashamed of, but staying week is."
];

console.log("Fortune cookie server starting..."); //Terminal text

/* Fortune generator function */
function generateFortuneCookieSaying() {
    const index = Math.floor(Math.random() * fortuneSayingsList.length); //Generate random index in plausible range of list of sayings
    return fortuneSayingsList[index]; //Return the saying with the generated index number
}

/* Request-response handler */
var handler = function (request, response) {
    console.log("Received request from " + request.connection.remoteAddress); //Terminal text
    response.writeHead(200); //OK status code 
    const str = generateFortuneCookieSaying(); //Fortune saying is generated by calling the above method
    console.log(str); //Terminal text: fortune saying
    response.end(str); //Fortune saying is returned to the requesting client
};

var www = http.createServer(handler); //Node.js server creation
www.listen(8080); //Node.js request port listening 
