apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-generator-deployment
  labels:
    app: fortune-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune-generator
  template:
    metadata:
      labels:
        app: fortune-generator
    spec:
      containers:
        - name: fortune-generator
          image: kristofferpbs/fortune_generator:v3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-generator-service
spec:
  type: NodePort
  selector:
    app: fortune-generator
  ports:
    - port: 80
      targetPort: 8080
